### ISSUE TITLE
fix the poor autotag robot on this repo

### ISSUE THREAD

**Issue by chee** [Financial-Times/remark-preset-lint-origami-component#24]
it keeps releasing updates to the older 0.x series instead of 1.x

**Comment by notlee** [comment]
`v1.1.3` and `v0.0.3` reference the same commit. Checking out `v1.1.3` and running `git describe --abbrev=0 --tags` (which `origami-version` runs) returns `v0.0.3`. Since `v1.1.3` was tagged after I'd expect it to be returned. 😕 

https://git-scm.com/docs/git-describe
>For each commit-ish supplied, git describe will first look for a tag which tags exactly that commit. Annotated tags will always be preferred over lightweight tags, and tags with newer dates will always be preferred over tags with older dates. If an exact match is found, its name will be output and searching will stop.

Running `git describe --abbrev=0 --tags` on master now `v1.2.0` is returned... so hopefully a new release will work...?

**Comment by notlee** [comment]
🙌 I don't understand the original issue but v1.2.1 was just released by fox correctly

I think I'm happy to close, unless you think it would be worth investigating futher @chee?

**Comment by JakeChampion** [comment]
Let's try some more releases before we close this 👍

**Comment by chee** [comment]
this seems like it's fixed!
